export { default as Board } from './BoardIcon'
export { default as Create } from './CreateIcon'
export { default as Invoices } from './InvoicesIcon'
export { default as Profile } from './ProfileIcon'
export { default as Settings } from './SettingsIcon'
export { default as Timers } from './TimersIcon'
